Repository WildCodeSchool/0322_P3_Php_Lyon_Salesforce, pull requests merged in 2023-06, with the labels that each got.

#12 S01 side navbar
  assets/app.js
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/logo.png
  assets/styles/_wcs.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/Form/IdeaType.php
  src/Repository/IdeaRepository.php
  templates/base.html.twig
  templates/component/_sideNavbar.html.twig
  templates/component/_topNavbar.html.twig
  templates/home/index.html.twig
  templates/idea/index.html.twig
  yarn.lock
Labels: Changes done

#15 S01 vue idées sur page accueil
  templates/home/index.html.twig
Labels: Changes done

#17 S01 side navbar
  assets/styles/app.scss
  templates/component/_sideNavbar.html.twig
Labels: Needs pair review

#25 Display categories on sideBar
  config/packages/twig.yaml
  src/Form/IdeaType.php
  src/Twig/PerimeterExtension.php
  templates/component/_sideNavbar.html.twig
Labels: Changes done, Needs pair review

#26 The user connection form has been created
  config/packages/security.yaml
  migrations/Version20230608073236.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/login/index.html.twig
Labels: Changes done

#31 Using Faker to generate a lot of users
  src/DataFixtures/IdeaFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Needs pair review

#32 S01 display ideas by perimeter and more recent
  src/Controller/HomeController.php
  src/Controller/IdeaController.php
  templates/component/_sideNavbar.html.twig
  templates/idea/ideaByPerimeter.html.twig
Labels: Needs pair review

#33 Us22 page admin liste utilisateurs
  assets/styles/app.scss
  composer.lock
  src/Controller/AdminController.php
  src/Controller/IdeaController.php
  templates/admin/users.html.twig
  templates/base.html.twig
  templates/component/_sideNavbar.html.twig
Labels: Changes done

#38 change the "ajouter une idée!" button text from black to white
  templates/component/_topNavbar.html.twig
Labels: Needs pair review

#39 S02 fix s01 perimeter field
  config/packages/translation.yaml
  config/packages/twig.yaml
  src/Controller/LoginController.php
  src/Controller/SecurityController.php
  src/DataFixtures/IdeaFixtures.php
  src/Entity/Idea.php
  src/Form/IdeaType.php
  src/Twig/PerimeterExtension.php
  templates/base.html.twig
  templates/components/_sideNavbar.html.twig
  templates/components/_topNavbar.html.twig
  templates/home/index.html.twig
  templates/idea/ideaByPerimeter.html.twig
Labels: Changes done

#40 S02 us19 form errors display
  assets/styles/app.scss
  config/packages/translation.yaml
  templates/idea/new.html.twig
  templates/login/index.html.twig
  translations/security.fr.yaml
Labels: Needs pair review

#41 23 update user page crud
  migrations/Version20230608140223.php
  src/Controller/AdminController.php
  src/Controller/UserController.php
  src/Form/UserType.php
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/new.html.twig
  templates/admin/user/show.html.twig
  templates/admin/users.html.twig
Labels: Changes done

#46 S02 entities update
  migrations/Version20230605094344.php
  migrations/Version20230605094624.php
  migrations/Version20230606100830.php
  migrations/Version20230608073236.php
  migrations/Version20230614082431.php
  migrations/Version20230615120455.php
  src/Controller/IdeaController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/IdeaFixtures.php
  src/DataFixtures/OfficeFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Idea.php
  src/Entity/Office.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/IdeaRepository.php
  src/Repository/OfficeRepository.php
  templates/admin/user/show.html.twig
  templates/admin/users.html.twig
  templates/components/_sideNavbar.html.twig
  templates/home/index.html.twig
  templates/idea/ideasByUserDepartment.html.twig
  templates/idea/ideasByUserOffice.html.twig
  templates/user/profil.html.twig
Labels: Changes done

#47 34 idea sticker
  src/Controller/IdeaController.php
  src/Form/IdeaType.php
  templates/home/index.html.twig
Labels: Changes done

#48 S02 us36 profil page
  assets/styles/app.scss
  src/Controller/UserController.php
  src/Service/ImageVerification.php
  templates/components/_sideNavbar.html.twig
  templates/user/profil.html.twig
Labels: Changes done

#50 49 idea stickers agency service
  src/Controller/IdeaController.php
  src/DataFixtures/IdeaFixtures.php
  src/Entity/Idea.php
  src/Repository/IdeaRepository.php
  templates/idea/ideasByUserDepartment.html.twig
  templates/idea/ideasByUserOffice.html.twig
Labels: Changes done

#55 IdeaFormHandler was created as a service to lighten the idea_new controller.
  src/Controller/IdeaController.php
  src/DataFixtures/IdeaFixtures.php
  src/Service/IdeaFormHandler.php
Labels: Changes done

#69 optimise the profile picture form code
  src/Controller/UserController.php
  src/Form/UserType.php
  src/Service/ImageVerification.php
  templates/user/profil.html.twig
Labels: Changes done

#74 S03 us61 show each idea in dédicate page
  assets/images/slack_logo.png
  assets/styles/app.scss
  composer.lock
  src/Controller/AdminController.php
  src/Controller/IdeaController.php
  src/DataFixtures/IdeaFixtures.php
  templates/admin/ideas.html.twig
  templates/components/_sideNavbar.html.twig
  templates/idea/show.html.twig
Labels: Changes done

#76 S03 users can delete their ideas
  assets/deleteIdea.js
  assets/styles/app.scss
  migrations/Version20230621092039.php
  src/Controller/AjaxController.php
  src/Controller/UserController.php
  src/DataFixtures/IdeaFixtures.php
  src/Entity/Idea.php
  src/Repository/IdeaRepository.php
  src/Service/IdeaFormHandler.php
  templates/home/index.html.twig
  templates/idea/ideasByUserDepartment.html.twig
  templates/idea/ideasByUserOffice.html.twig
  templates/user/profil.html.twig
  webpack.config.js
Labels: Changes done

#77 Smoke test
  .github/workflows/main.yml
  composer.lock
  src/DataFixtures/IdeaFixtures.php
  src/Service/ImageVerification.php
  tests/RoutesTest.php
Labels: Needs pair review

#81 S04 us65 slack api
  .env
  src/Controller/SlackController.php
  src/Service/SlackService.php
  templates/slack/createchannel.html.twig
  templates/slack/index.html.twig
Labels: Needs pair review

#78 S03 hotfix adding delete button on idea page
  assets/deleteIdea.js
  templates/idea/show.html.twig
Labels: Changes done

#93 S04 us80 user can adhere to an idea
  migrations/Version20230626120347.php
  src/Controller/IdeaController.php
  src/Controller/UserController.php
  src/Entity/Idea.php
  src/Entity/Membership.php
  src/Entity/User.php
  src/Repository/IdeaRepository.php
  src/Repository/MembershipRepository.php
  src/Service/BecomeIdeaMember.php
  templates/idea/show.html.twig
  templates/user/profil.html.twig
Labels: Changes done
